/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagement;

import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.Supplier;
import javax.swing.JPanel;
import java.util.HashMap;



/**
 *
 * @author kal bugrara
 */
public class ManageProductPerformanceDetail extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    Business business;
    JPanel CardSequencePanel;
    Product selectedproduct;
    
    HashMap<String, Product> productMap = new HashMap<>();

     public ManageProductPerformanceDetail(Business business, Product product, JPanel jpl) {

        this.business = business;
        this.selectedproduct = product;
        this.CardSequencePanel = jpl;
        initComponents();
        populateProductDropdown();
        displayProductPerformance();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        productFrequencyAboveTargetTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productRevenueTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productFrequencyBelowTargetTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productPricePerformanceTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lowerPriceBtn = new javax.swing.JButton();
        increasePriceBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Product Performance Summary");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 550, -1));

        jLabel3.setText("Product name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        productNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextFieldActionPerformed(evt);
            }
        });
        add(productNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 63, 330, 60));
        add(productFrequencyAboveTargetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 160, -1));

        jLabel4.setText("Frequency Above Target");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, 20));

        productRevenueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productRevenueTextFieldActionPerformed(evt);
            }
        });
        add(productRevenueTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        jLabel5.setText("Sales Revenues");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));
        add(productFrequencyBelowTargetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 160, -1));

        jLabel6.setText("Frequency Below Target");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 150, 20));

        productPricePerformanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPricePerformanceTextFieldActionPerformed(evt);
            }
        });
        add(productPricePerformanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 30));

        jLabel7.setText("Marign around target");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 160, 20));

        lowerPriceBtn.setText("Lower Price");
        lowerPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerPriceBtnActionPerformed(evt);
            }
        });
        add(lowerPriceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, 20));

        increasePriceBtn.setText("Increase Price");
        increasePriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increasePriceBtnActionPerformed(evt);
            }
        });
        add(increasePriceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 220, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_BackActionPerformed

    private void productNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextFieldActionPerformed

    private void productRevenueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productRevenueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productRevenueTextFieldActionPerformed

    private void productPricePerformanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPricePerformanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPricePerformanceTextFieldActionPerformed

    private void lowerPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerPriceBtnActionPerformed
        // TODO add your handling code here:
    int oldTarget = selectedproduct.getTargetPrice();
    int below = selectedproduct.getNumberOfProductSalesBelowTarget();
    int above = selectedproduct.getNumberOfProductSalesAboveTarget();

    if (below <= above) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Product sales are not below target — no need to lower price.");
        return;
    }

    int newTarget = (int)(oldTarget * 0.9); // 降 10%
    selectedproduct.updateProduct(
        selectedproduct.getFloorPrice(),
        selectedproduct.getCeilingPrice(),
        newTarget
    );

    javax.swing.JOptionPane.showMessageDialog(this, 
        "Target price lowered from $" + oldTarget + " → $" + newTarget);

    refreshTable(); 
    
    }//GEN-LAST:event_lowerPriceBtnActionPerformed

    private void increasePriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increasePriceBtnActionPerformed
        // TODO add your handling code here:
         int oldTarget = selectedproduct.getTargetPrice();
    int below = selectedproduct.getNumberOfProductSalesBelowTarget();
    int above = selectedproduct.getNumberOfProductSalesAboveTarget();

    if (above <= below) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Product sales have not surpassed target — cannot increase price.");
        return;
    }

    int newTarget = (int)(oldTarget * 1.1);
    selectedproduct.updateProduct(
        selectedproduct.getFloorPrice(),
        selectedproduct.getCeilingPrice(),
        newTarget 
    );

    javax.swing.JOptionPane.showMessageDialog(this, 
        "Target price increased from $" + oldTarget + " → $" + newTarget);

    refreshTable();
    }//GEN-LAST:event_increasePriceBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         String name = (String) jComboBox1.getSelectedItem();

        if (name != null && productMap.containsKey(name)) {
            selectedproduct = productMap.get(name);
            displayProductPerformance();
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton increasePriceBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton lowerPriceBtn;
    private javax.swing.JTextField productFrequencyAboveTargetTextField;
    private javax.swing.JTextField productFrequencyBelowTargetTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JTextField productPricePerformanceTextField;
    private javax.swing.JTextField productRevenueTextField;
    // End of variables declaration//GEN-END:variables

    private void displayProductPerformance() {
        if (selectedproduct == null) return;

        ProductSummary productsummary = new ProductSummary(selectedproduct);

        productNameTextField.setText(selectedproduct.toString());
        productRevenueTextField.setText(String.format("%.2f", productsummary.getSalesRevenues()));
        productFrequencyAboveTargetTextField.setText(String.valueOf(productsummary.getNumberAboveTarget()));
        productFrequencyBelowTargetTextField.setText(String.valueOf(productsummary.getNumberBelowTarget()));
        productPricePerformanceTextField.setText(String.format("%.2f%%", productsummary.getProductPricePerformance()));
    }
    
    private void refreshTable() {
        displayProductPerformance();
    }

    private void populateProductDropdown() {

        jComboBox1.removeAllItems();
        productMap.clear();

        for (Supplier supplier : business.getSupplierDirectory().getSuplierList()) {
            for (Product product : supplier.getProductCatalog().getProductList()) {

                String name = product.toString();
                jComboBox1.addItem(name);
                productMap.put(name, product);
            }
        }
    }

}
